#!/bin/sh

DIRNAME="/usr/share/stegosuite"
STEGOSUITEJAR=$(echo $DIRNAME/stegosuite-*.jar)

# Setup the classpath
if [ ! -f "$STEGOSUITEJAR" ]; then
    >&2 echo "Missing required file: $STEGOSUITEJAR"; exit 1
fi

STEGOSUITE_CLASSPATH="$STEGOSUITEJAR"

java -jar "$STEGOSUITE_CLASSPATH" "$@"
